### PR TITLE
Issue with storing session objects rather than as, say, JSON string.

### PR DESCRIPTION
**Pull request by jfgorski**
Hi, not sure if there's another way around this problem, or if it's due to the combination of module versions I'm using. I ran into issues with the session being stored as an object in mongodb since it stores the session cookie field originalMaxAge as NumberLong, and the mongodb module I'm using returns this as an object in the JS value, but then connect's maxAge setter gets confused since it's looking for a number type. So, I had to switch to storing the sessions as JSON strings (like the connect-redis module).

### CODE REVIEW

**Comment by masylum** [comment]
There is some people asking for this change. Although when I had the session as a string people was complaining and asking me to store the object.

I don't really know what to do. Votes?

+1 store as a string

**Comment by sir-pinecone** [comment]
+1 for string

**Comment by Charuru** [comment]
+1 string

**Comment by c4milo** [comment]
+1 string

**Comment by masylum** [comment]
done

**Comment by niftylettuce** [comment]
This doesn't make sense, you can't retrieve any data that is stored in the DB since its stored as a string?  Defeats purpose of JSON db schemas e.g. Mongoose.

**Comment by masylum** [comment]
Then fork the project and use that fork.
I had the non-stringified version and lots of issues happened with the connect session middleware and BSON encoding.\

I personally don't feel like maintaining those issues anymore :)

**Pull request closed without merging**
