### PR TITLE
Update connect version

### PR DESCRIPTION
**Pull request by Raynos**
for 0.8 support

### CODE REVIEW

**Comment by cleishm** [comment]
+1

**Comment by tleach** [comment]
+1

**Comment by djhojd** [comment]
+1

**Comment by RobertRShaw** [comment]
+1

**Comment by jsantell** [comment]
+1

**Comment by diogogmt** [comment]
+1

While the module is not updated, what is the best approach to take?
I can't simple just use connect 1.8.5 since I already updated node to the 0.8.2 version

**Comment by Raynos** [comment]
@diogogmt https://github.com/Raynos/connect-mongodb

Specifically: https://github.com/Raynos/connect-mongodb/commit/68a4f8f2883baa6891c824355f7c3c5e55719a1d

Use like `mongodb: git@github.com:Raynos/connect-mongodb`

**Comment by diogogmt** [comment]
That's what I did here, I just bumped the version number.
But why not have the version as "connect": ">= 1.8.5" ?

Is there any features being used that required a specific version of connect?

**Comment by Raynos** [comment]
@diogogmt static version numbers are always more stable. some newer versions break

**Comment by cleishm** [comment]
@raynos That's what the ~ notation is for `"connect": "~ 1.8.5"`.

**Comment by zdwalter** [comment]
+1

**Comment by nleush** [comment]
+1

**Pull request merged**
