### PR TITLE
Possibility to use existing connection

### PR DESCRIPTION
**Pull request by tedeh**
Hello,

Here are some commits that will enable reusing of an existing connection or server configuration instead of forcing the opening of a new one. Also added corresponding information in the readme. I would have added some tests too but the tests in the repository were removed in 217cc3aa6f4e79e8f05011e11d593c4c1d02615d (mistake?!). 

Also I believe that the existing ad hoc implementation of Replica Sets should be removed: a user intending to use an adanced MongoDB configuration should be prepared to setup the appropriate connection using christkv/node-mongodb-native anyway. Besides, it seems reasonable that such a user has done that setup already. I would have done it but I'm floating it for discussion here first.

### CODE REVIEW

**Comment by masylum** [comment]
I will take a look tomorrow. So far, it looks really good.

I removed the tests because they where outdated and useless. 
I will add new tests as soon as possible.

About removing the replica sets, it would simplify the module by delegating the implementation to the user. I'm just a little bit worried about backwards compatibility.

**Comment by tedeh** [comment]
I'm adding another commit which is pretty self-explanatory. `_default()` now also typeof-checks the callback for a function, which ensures that whatever is being passed in can _actually_ be called later.

**Comment by tedeh** [comment]
One could begin by moving the ad hoc ReplicaSet implementation out of the `MongoStore` constructor and into a separate function which could do a console.warn() about deprecation every time called. Keep it like that for a few versions and then remove it, maybe.

**Comment by masylum** [comment]
I'm merging now, but I will not bump and publish the npm version until I write some tests.

**Comment by tedeh** [comment]
Thanks, sounds reasonable.

**Pull request merged**
